Nucleotides="ATGGCAGAAACGCCCTTATTCAATTTCCGGAGACGTCATATTTTCTAGAACTTGACATACGCGTGAAATCAATTCCTCCATTGGGACTGTTAGATTTAGAATGATGCTCCGCTCCACGTCTGGTCTCAAACTATCAACCGGATAGGAAACTTTGGCGTATATACGCAACATAAGGCGTCCAGGGCCAGTGTATAAAACGCACATAACCCACATATAAGTTGTTATCCAAGTTATCCGCATTTTCAAGCGCGATTTAGGTTGACGGCGAGTCTACTATGCTACCTGAAGGTTGAAGGATGCGTGTAAGCCCCTCTGGATCTTTACGATACGCAACTTCTCTTTACTGTACACTCCTCATATAGGAAATCTCGCAACTGCTTCGGCTTCCGCTTAACATACGACCAGGCGGGAGTGTACATGTTACTGCTATACCACGTATCCTGGCTCCCGGGCAGCGGTCCAAGGAATCTGGGGTTATGAGCCATTGTTGGAACGGACGTCTGAAGTTGGCGATCACGCCCTGCATGATCACGTGTACAGTTGTCAATCTCGGTCTCAACCTACCCAATTTGGAACGCCCGGTGAATCGCTGAACCATTGGAAAACAGGCGCTTGTGAGCTGTGGGATAAGGGATGAAGAGATGTATAAACGAATTGCATGGAACTCCATGAAACTGGAGGAGCTCAATGTCTACAGTCTATTTTGGATGAGACCTCCCTCCATCTCATACCGAGCCTGTGGTTCCATATGCCTTATCGGCAACCGGTGGTACTCAGAAGAAATTCGGCGAGTCCATCGGTCTTGAGATTCCATTGGCAAGATAACACCCATATGCAACTATGCTGGCTACGAGTGATTCCCTCGGAGGCAAGGTCGCTGAACGTTTCCTCTAACTTAATATTTATCCGCCTGTTCTCAGGATCTGG"
Acounter = 0
Ccounter = 0
Gcounter = 0
Tcounter = 0

for c in Nucleotides:
    if c == 'A':
        Acounter+=1
    elif c == 'T':
        Tcounter+=1
    elif c == 'C':
        Ccounter+=1
    elif c == 'G':
        Gcounter+=1
print("{} {} {} {}".format(Acounter, Ccounter, Gcounter, Tcounter))